Fix the bug 'AttributeError: 'str' object has no attribute '_sa_instance_state'
In the previous version, in line 18, the ORM was querying for the "device_id", instead of for the "name" of the device.

Furthermore, on line 27, during the "new_user" creation, a string (the one inserted by the user) was assigned to the attribute "device", instead of the object resulting from the query in line 18.